name: FedBO
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - scipy=1.12.0
  - scikit-learn=1.6.1
  - matplotlib=3.9.4
  - pandas=2.3.3
  - openpyxl=3.1.5
  - cython=3.1.4
  - pip:
      - gpy==1.13.2
      - paramz==0.9.6
      - scikit-optimize==0.10.2
      - pyaml==25.7.0
      - pyyaml==6.0.3
      - bayesian-optimization
